-- SPDX-License-Identifier: AGPL-3.0-only
-- Complete host rollup schema for broadened telemetry (SPEC §24.3).

-- host_rollups_1m
ALTER TABLE host_rollups_1m ADD COLUMN cpu_user_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_user_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_user_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_user_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_system_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_system_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_system_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_system_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_iowait_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_iowait_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_iowait_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_iowait_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_steal_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_steal_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_steal_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN cpu_steal_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN load_1_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_1_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_1_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_1_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN load_5_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_5_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_5_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_5_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN load_15_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_15_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_15_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN load_15_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN swap_used_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN swap_used_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN swap_used_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN swap_used_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN disk_read_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_read_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_read_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_read_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN disk_write_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_write_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_write_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_write_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN disk_iops_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_iops_avg REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_iops_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN disk_iops_count INTEGER NOT NULL DEFAULT 0;

-- host_rollups_15m
ALTER TABLE host_rollups_15m ADD COLUMN cpu_user_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_user_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_user_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_user_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_system_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_system_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_system_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_system_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_iowait_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_iowait_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_iowait_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_iowait_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_steal_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_steal_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_steal_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN cpu_steal_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN load_1_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_1_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_1_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_1_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN load_5_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_5_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_5_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_5_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN load_15_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_15_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_15_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN load_15_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN swap_used_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN swap_used_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN swap_used_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN swap_used_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN disk_read_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_read_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_read_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_read_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN disk_write_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_write_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_write_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_write_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN disk_iops_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_iops_avg REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_iops_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN disk_iops_count INTEGER NOT NULL DEFAULT 0;

-- host_rollups_1h
ALTER TABLE host_rollups_1h ADD COLUMN cpu_user_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_user_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_user_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_user_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_system_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_system_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_system_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_system_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_iowait_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_iowait_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_iowait_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_iowait_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_steal_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_steal_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_steal_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN cpu_steal_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN load_1_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_1_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_1_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_1_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN load_5_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_5_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_5_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_5_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN load_15_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_15_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_15_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN load_15_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN swap_used_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN swap_used_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN swap_used_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN swap_used_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN disk_read_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_read_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_read_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_read_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN disk_write_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_write_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_write_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_write_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN disk_iops_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_iops_avg REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_iops_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN disk_iops_count INTEGER NOT NULL DEFAULT 0;
